---
- name: Ensure required apt packages are installed
  apt:
    autoremove: yes
    cache_valid_time: 3600
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  become: yes
  with_items:
    - apt-transport-https
    - bzip2
    - ca-certificates
    - chromium-browser
    - curl
    - git
    - jmeter
    - language-pack-en
    - maven
    - nano
    - subversion
    - virtualbox-guest-dkms
    - virtualbox-guest-utils
    - virtualbox-guest-x11

- name: Set locale
  set_fact:
    default_locale: "en_US.UTF-8"

- name: Generate locales
  locale_gen: name={{ default_locale }} state=present

- name: Set default locale
  become: yes
  template: src=locale.j2 dest=/etc/default/locale

- name: Add bash aliases
  lineinfile:
    dest: "{{ bash_aliases_path }}"
    create: yes
    mode: 0644
    line: 'alias {{ item.alias }}="{{ item.command }}"'
    regexp: "^alias {{ item.alias }}="
  with_items: '{{bash_aliases}}'
