---
- name: set download location on master
  set_fact:
    master_download_folder: "{{ ansible_env.PWD ~ '/downloads' }}"
  delegate_to: local
  run_once: true

- name: create downloads folder if it does not exist yet
  file:
    dest: "{{ master_download_folder }}"
    state: directory

- name: Configure facts
  set_fact:
    install_dir:  "{{ ansible_env.HOME ~ '/sw/oracle' }}"
    sqldeveloper_archive_path: "{{ master_download_folder ~ '/sqldeveloper.zip' }}"

- name: Check if Oracle SQL Developer archive is present
  stat:
    path: "{{ sqldeveloper_archive_path }}"
  register: sqldeveloper_archive

- name: Create install directory
  file:
    dest: "{{ install_dir }}"
    state: directory
  when: sqldeveloper_archive.stat.exists == True

- name: set name of unpacked Oracle SQL Developer directory
  set_fact:


- name: unpack archive from master
  unarchive:
    src:     "{{ sqldeveloper_archive_path }}"
    dest:    "{{ install_dir }}"
    creates: "{{ install_dir ~ '/sqldeveloper/sqldeveloper.sh' }}"
  when: sqldeveloper_archive.stat.exists == True
