---
- name: Set locale
  set_fact:
    default_locale: "en_US.UTF-8"

- name: Generate locales
  locale_gen: name={{ default_locale }} state=present

- name: Set default locale
  become: yes
  template: src=locale.j2 dest=/etc/default/locale
