---
- name: Ensure required apt packages are installed
  apt:
    autoremove: yes
    cache_valid_time: 3600
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  become: yes
  with_items:
    - apt-transport-https
    - bzip2
    - ca-certificates
    - chromium-browser
    - curl
    - git
    - jmeter
    - language-pack-en
    - maven
    - nano
    - subversion
    - virtualbox-guest-dkms
    - virtualbox-guest-utils
    - virtualbox-guest-x11
