---
  - hosts: all
    gather_facts: yes
    pre_tasks:
      - name: Ensure required apt packages are installed
        apt:
          autoremove: yes
          cache_valid_time: 3600
          pkg: "{{ item }}"
          state: present
          update_cache: yes
        become: yes
        with_items:
          - apt-transport-https
          - bzip2
          - ca-certificates
          - curl
          - gzip
          - language-pack-en
          - tar
          - unzip
      - name: Ensure additional apt packages are installed
        apt:
          autoremove: yes
          cache_valid_time: 3600
          pkg: "{{ item }}"
          state: present
          update_cache: yes
        become: yes
        with_items:
          - bmon
          - bridge-utils
          - chromium-browser
          - git
          - imagemagick
          - jmeter
          - maven
          - subversion
    post_tasks:
      - name: Ensure required pip packages are installed
        pip:
          name: "{{ item }}"
          state: present
        become: yes
        with_items:
          - sqlparse
      - name: select Java 8 JRE as default java
        alternatives: name=java path=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
      - name: Add vagrant user to docker group
        become: yes
        user:
          groups: "docker"
          name: vagrant
    roles:
      - role: stevenharradine.locale
        locale_locales:
          - en_US.UTF-8
      - { role: geerlingguy.java, become: yes, java_packages: ['openjdk-8-jdk'] }
      - role: ferrarimarco.xfce
        become: yes
      - ferrarimarco.eclipse
      - { role: ferrarimarco.docker, become: yes }
      - role: ferrarimarco.ruby
        become: yes
      - role: ferrarimarco.atom
        become: yes
        ferrarimarco_atom_become_users:
          - username: ferrarimarco
            atom_packages:
              - atom-beautify
              - autocomplete-plus
              - autocomplete-python
              - color-picker
              - file-icons
              - hyperclick
              - language-ansible
              - language-docker
              - linter
              - pigments
              - minimap
      - role: ferrarimarco.nano
        become: yes
      - role: ferrarimarco.bash-aliases
        bash_aliases:
          - { alias: "changelog-generator", command: 'docker run -it --rm -v "$(pwd)":/app prooph/github-changelog-generator' }
          - { alias: "docker-clean", command: 'docker run --rm -v /var/run/docker.sock:/var/run/docker.sock zzrot/docker-clean' }
          - { alias: "git-log1", command: 'docker run -it --rm -v "$(pwd)":/usr/src -w /usr/src --rm ferrarimarco/open-development-environment-git:1.0.1 lg1' }
          - { alias: "git-log2", command: 'docker run -it --rm -v "$(pwd)":/usr/src -w /usr/src --rm ferrarimarco/open-development-environment-git:1.0.1 lg2' }
          - { alias: "git-log3", command: 'docker run -it --rm -v "$(pwd)":/usr/src -w /usr/src --rm ferrarimarco/open-development-environment-git:1.0.1 lg3' }
        become: yes
      - role: ferrarimarco.virtualbox
        become: yes
      - role: ferrarimarco.vagrant
        become: yes
      - role: ferrarimarco.oracle-sql-developer
        ferrarimarco_oracle_sql_dev_archive_path: "{{ ansible_env.PWD ~ '/downloads/sqldeveloper-no-jre.zip' }}"
