---
  - hosts: all
    gather_facts: yes
    pre_tasks:
      - name: Installing apt repository for Java 8
        apt_repository: repo='ppa:openjdk-r/ppa'
        become: yes
        when: ansible_distribution == 'Ubuntu'
    post_tasks:
      - name: select Java 8 JRE as default java
        alternatives: name=java path=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
    roles:
      - role: stevenharradine.locale
        locale_locales:
          - en_US.UTF-8
      - { role: geerlingguy.java, become: yes, java_packages: ['openjdk-8-jdk'] }
      - { role: ansible-role-devbox-base }
      - { role: ferrarimarco.docker, become: yes }
      - role: ferrarimarco.ruby
        become: yes
      - { role: ferrarimarco.atom, become: yes }
      - role: ferrarimarco.nano
        become: yes
      - role: ferrarimarco.bash-aliases
        bash_aliases:
          - { alias: "changelog-generator", command: 'docker run -it --rm -v "$(pwd)":/app prooph/github-changelog-generator' }
          - { alias: "docker-clean", command: 'docker run --rm -v /var/run/docker.sock:/var/run/docker.sock zzrot/docker-clean' }
          - { alias: "git-log1", command: 'docker run -it --rm -v "$(pwd)":/usr/src -w /usr/src --rm ferrarimarco/open-development-environment-git:1.0.1 lg1' }
          - { alias: "git-log2", command: 'docker run -it --rm -v "$(pwd)":/usr/src -w /usr/src --rm ferrarimarco/open-development-environment-git:1.0.1 lg2' }
          - { alias: "git-log3", command: 'docker run -it --rm -v "$(pwd)":/usr/src -w /usr/src --rm ferrarimarco/open-development-environment-git:1.0.1 lg3' }
        become: yes
