---
dependencies: []

galaxy_info:
  author: ferrarimarco
  description: Install XFCE
  license: "license (Apache 2.0)"
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
      - trusty
      - vivid
      - xenial
  galaxy_tags:
    - desktop
    - xfce
